name: easy_units
description: "Universal Unit Converter"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.9+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  dio: ^5.4.2+1
  retrofit: '>=4.0.0 <5.0.0'
  logger: any  #for logging purpose
  json_annotation: ^4.8.1
  get_it: ^7.6.9
  injectable: ^2.4.1
  equatable: ^2.0.5
  auto_route: ^8.1.3
  units_converter: ^3.0.0
  flutter_native_splash: ^2.4.0
  home_widget: ^0.5.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^3.1.0

  eu_uikit:
    path: ./packages/eu_uikit

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  auto_route_generator: ^8.0.0
  retrofit_generator: '>=7.0.0 <8.0.0'   # required dart >=2.19
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.7.1
  injectable_generator: ^2.6.1

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/easy_unit_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  adaptive_icon_padding: false

flutter_native_splash:
  ios: false
  color: "#ffffff"
  image: assets/images/launcher_image.png
  color_dark: "#202020"
  image_dark: assets/images/launcher_image.png

  android: true
  android_12:
    image: assets/images/launcher_image.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/launcher_image.png
    icon_background_color_dark: "#202020"

  web: false

flutter:
  uses-material-design: true
